---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Image:
    Type: String
  ECSCluster:
    Type: String
Resources:
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Sub ${AWS::StackName}-WebApiSample
      ContainerDefinitions:
        - Name: webapisample
          Image: !Ref Image
          MemoryReservation: 256
          PortMappings:
            - ContainerPort: 80
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      PlacementStrategies:
        - Type: spread
          Field: instanceId
      TaskDefinition: !Ref TaskDefinition